APPDEVInc2/ViewModels/Mechanic/CalloutReportCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using APPDEVInc2.DataBaseModels;
namespace APPDEVInc2.ViewModels.Mechanic
{
    public class CalloutReportCartViewModel
    {
        public List<CalloutReportCart> CartItems { get; set; }

        //[DataType(DataType.Currency)]
        public decimal CartTotal { get; set; }
    }
}

APPDEVInc2/Controllers/CalloutReportCartController.cs
using APPDEVInc2.Models;
using APPDEVInc2.ViewModels.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPDEVInc2.Repository;
using APPDEVInc2.DataBaseModels;
using Microsoft.AspNet.Identity;
using System.Data;
using IronBarCode;
using System.Drawing;
using System.IO;
using APPDEVInc2.ViewModels.Mechanic;

namespace APPDEVInc2.Controllers
{
    public class CalloutReportCartController : Controller
    {
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Cart
        public ActionResult Index()
        {
            var cart = CalloutReportingCart.GetCart(this.HttpContext);
            var viewModel = new CalloutReportCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);

            // var cart = _unitOfWork.GetRepositoryInstance<Cart>().GetAllRecordsIQueryable();
            // Set up our ViewModel

            // Return the view
            //var viewModel = cart;

        }
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProduct = db.CalloutServices
                .Single(product => product.CalloutServiceID == id);

            // Add it to the shopping cart
            var cart = CalloutReportingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main Quotation Items to add
            return RedirectToAction("ReportForCalloutStart", "Mechanic", new { id = Int32.Parse(Session["CalloutID"] + "") });
        }

        // Increase QTY Checkout
        public ActionResult IncreaseQTY(int id)
        {
            HttpContext context = System.Web.HttpContext.Current;
            // var prods = db.TyresTbls.Single(a => a.TyreID == id);
            var x = db.CalloutServices.Single(a => a.CalloutServiceID == id);
            string cid = "";

            int stockid = x.CalloutServiceID;

            var cart1 = _unitOfWork.GetRepositoryInstance<CalloutReportCart>().GetAllRecords();
            var last = cart1.Last();
            cid = context.User.Identity.Name;

            string cartid = context.Session["ReportCartId"].ToString();
            if (cid != null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.CalloutReportCarts.Where(a => a.VehicleID == cartid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cartid && item.CalloutServiceID == id)
                        {
                            item.Count += 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.CalloutReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };
            }
            if (cid == null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.CalloutReportCarts.Where(a => a.VehicleID == cartid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cid && item.CalloutServiceID == id)
                        {
                            item.Count += 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.CalloutReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };

            }


            return RedirectToAction("Index");
        }

        // Decrease QTY Checkout
        public ActionResult DecreaseQTY(int id)
        {
            HttpContext context = System.Web.HttpContext.Current;
            var car = new CalloutReport();
            string cid = "";
            var x = db.CalloutServices.Single(a => a.CalloutServiceID == id);
            int stockid = x.CalloutServiceID;

            var cart1 = _unitOfWork.GetRepositoryInstance<CalloutReportCart>().GetAllRecords();
            var last = cart1.Last();
            cid = context.User.Identity.Name;
            string cartid = context.Session["ReportCartId"].ToString();

            if (cid != null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.CalloutReportCarts.Where(a => a.VehicleID == cartid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cartid && item.CalloutServiceID == id)
                        {
                            item.Count -= 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.CalloutReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };
            }
            if (cid == null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.CalloutReportCarts.Where(a => a.VehicleID == cid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cid && item.CalloutServiceID == id)
                        {
                            item.Count -= 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.CalloutReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };

            }

            return RedirectToAction("Index");
        }

        public ActionResult CheckoutDetail()
        {

            string name = this.HttpContext.User.ToString();


            var cart = CalloutReportingCart.GetCart(this.HttpContext);

            var viewModel = new CalloutReportCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()

            };

            return View(viewModel);
        }

        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CalloutReportCartSummary() 
        {
            var cart = CalloutReportingCart.GetCart(this.HttpContext);

            ViewData["CalloutReportCartCount"] = cart.GetCount();
            return PartialView("CalloutReportCartSummary");
        }

    }
}

APPDEVInc2/Views/CalloutReportCart/CalloutReportCartSummary.cshtml
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>
<body>


    <a class="nav-link fa fa-shopping-cart" @Html.ActionLink(" (" + ViewData["CalloutReportCartCount"] + ")", "Index", "CalloutReportingCart", new { id = "cart-status" })</a>


</body>
</html>

APPDEVInc2/Views/CalloutReportCart/Index.cshtml
@model APPDEVInc2.ViewModels.Mechanic.CalloutReportCartViewModel

@{
    ViewData["Title"] = "Report Callout |";
    Layout = "~/Views/Shared/_LayoutMechanic.cshtml";
}

<br />
<br />
<br />
<br />
<partial name="_StatusMessage" model="@Model.CartTotal" />
<form method="post">
    @{
        decimal tyrestotal = 0;
        decimal servicetotal = 0;
    }
    @if (Model.CartItems.Count > 0)
    {
        <br />
        <input id="userId" asp-for="@Model.CartItems[0].VehicleID" hidden />

        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Callout Report Summary
                    </div>
                    <div class="col-6 text-right">
                        <input type="button" class="btn btn-info btn-sm" value="Continue Report" onclick="location.href='@Url.Action("GenerateReport", "Mechanic")'" />


                    </div>
                </div>
                <div class="card-body">
                    @foreach (var item in Model.CartItems)
                    {



                        <div class="row">
                           
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h4><strong>@item.CalloutServices.Name</strong></h4>
                                    <h4><small>@item.CalloutServices.Description</small></h4>
                                   
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>R @item.CalloutServices.Price <span class="text-muted">x</span>@item.Count </strong></h6>
                                        <h5><strong>Item Total : R @(item.CalloutServices.Price*item.Count) </strong></h5>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            <a href="@Url.Action("IncreaseQTY", "CalloutReportCart", new { id = item.CalloutServiceID})">
                                                <i class="fa fa-plus" style="color: #a721bb;font-size:20px"></i>
                                            </a>

                                        </div>
                                        <div class="float-right mx-1">
                                            <a href="@Url.Action("DecreaseQTY", "CalloutReportCart", new { id = item.CalloutServiceID})">
                                                <i class="fa fa-minus" style="color: #a721bb;font-size:20px"></i>
                                            </a>

                                        </div>
                                    </div>

                                </div>
                            
                           @{ 
                               servicetotal += (decimal)(item.CalloutServices.Price * item.Count);
                           }


                        </div><hr />

                               }
                   
                    <h4><strong>Services Total : R @(servicetotal)</strong></h4>
                    <h2><strong>Callout Report Total : R @(servicetotal)</strong></h2>

                </div>

            </div>


        </div>
        <button type="submit" class="btn btn-success center-block" ; style="background-color: #52eb34;
        color: black;
        font-size: 18px;
        font-weight: bold;
        border-color: #008000;
        text-align: center;
        width: 148px;">
            @Html.ActionLink("Proceed >>> ", "SelectVehicleCallout", "Mechanic")
        </button>
    }
    else
    { <br />
        <br />
        <br />
        <h2><strong>Your Callout Report Summary is Empty :(</strong></h2>
    }


</form>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}