APPDEVInc2/ViewModels/Mechanic/CalloutReportCartRemoveViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace APPDEVInc2.ViewModels.Mechanic
{
    public class CalloutReportCartRemoveViewModel
    {
        public string Message { get; set; }
        public decimal CartTotal { get; set; }
        public int CartCount { get; set; }
        public int ItemCount { get; set; }
        public int DeleteId { get; set; }
    }
}

APPDEVInc2/ViewModels/Mechanic/CalloutReportCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using APPDEVInc2.DataBaseModels;
namespace APPDEVInc2.ViewModels.Mechanic
{
    public class CalloutReportCartViewModel
    {
        public List<CalloutReportCart> CartItems { get; set; }

        //[DataType(DataType.Currency)]
        public decimal CartTotal { get; set; }
    }
}

APPDEVInc2/Controllers/MechanicController.cs
using APPDEVInc2.Models;
using APPDEVInc2.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPDEVInc2.DataBaseModels;
using System.Net.Mail;
using System.Net;

namespace APPDEVInc2.Controllers
{

     [Authorize(Roles = "Mechanic")]
    public class MechanicController : Controller
    {
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Mechanic
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult ViewCurrentBookedVehicles()
        {
            string username = this.User.Identity.Name;
            var mechanicid = _unitOfWork.GetRepositoryInstance<MechanicTbl>().GetAllRecordsIQueryable().Where(a => a.UserID == username);
            int mechid = 0;
            foreach (var item in mechanicid)
            {
                mechid = item.MechanicID;
            }



            return View(_unitOfWork.GetRepositoryInstance<ScheduleTbl>().GetAllRecordsIQueryable().Where(a => a.MechanicID == mechid && a.Status == "Pending"));
        }

        public ActionResult AcceptBooking(int id)
        {
            using (var dbs = new ApplicationDbContext())
            {
                var checkin = dbs.ScheduleTbls.Where(a => a.ScheduleID == id).ToList();

                foreach (var item in checkin)
                {
                    item.Status = "Accepted";

                    dbs.SaveChanges();
                }
            };
            return RedirectToAction("ViewAcceptedBookings", "Mechanic");
        }

        public ActionResult ViewAcceptedBookings()
        {
            string username = this.User.Identity.Name;
            var mechanicid = _unitOfWork.GetRepositoryInstance<MechanicTbl>().GetAllRecordsIQueryable().Where(a => a.UserID == username);
            int mechid = 0;
            foreach (var item in mechanicid)
            {
                mechid = item.MechanicID;
            }
            return View(_unitOfWork.GetRepositoryInstance<ScheduleTbl>().GetAllRecordsIQueryable().Where(a => a.CheckedIn == false && a.MechanicID == mechid && a.Status == "Accepted"));

        }

        public ActionResult CheckInVehicle(int id)
        {
            int bookid = 0;
            using (var dbs = new ApplicationDbContext())
            {
                var checkin = dbs.ScheduleTbls.Where(a => a.ScheduleID == id).ToList();

                foreach (var item in checkin)
                {
                    item.Status = "CheckIn";
                    item.CheckedIn = true;
                    item.DateCheckIn = DateTime.Now;
                    bookid = item.BookingID;
                    dbs.SaveChanges();
                }
            };

            //Sets status of Bays and Mechanic
            using (var x = new ApplicationDbContext())
            {
                int bayid = 0;
                var avail = x.BookingTbls.Where(a => a.BookingID == bookid).ToList();

                foreach (var item in avail)
                {
                    bayid = item.BayID;
                }
                var bays = x.BayTbls.Where(a => a.BayID == bayid).ToList();
                foreach (var a in bays)
                {
                    a.IsAvailable = false;
                    x.SaveChanges();
                }

                var mechanic = x.MechanicTbls.Where(a => a.UserID == this.User.Identity.Name).ToList();
                foreach (var mech in mechanic)
                {
                    mech.IsAvailable = false;
                    x.SaveChanges();
                }

            }
            return RedirectToAction("ViewCurrentMechanicalWork", "Mechanic");
        }

        public ActionResult ViewCurrentMechanicalWork()
        {
            string username = this.User.Identity.Name;
            var mechanicid = _unitOfWork.GetRepositoryInstance<MechanicTbl>().GetAllRecordsIQueryable().Where(a => a.UserID == username);
            int mechid = 0;
            foreach (var item in mechanicid)
            {
                mechid = item.MechanicID;
            }
            return View(_unitOfWork.GetRepositoryInstance<ScheduleTbl>().GetAllRecordsIQueryable().Where(a => a.CheckedIn == true && a.MechanicID == mechid && a.Status == "CheckIn"));
        }

        public ActionResult GenerateReport(int id)
        {
            Session["Vechid"] = id;
            return View(_unitOfWork.GetRepositoryInstance<StockTbl>().GetAllRecords().ToList());
        }


        public ActionResult ReportCommit()
        {
            int vehicleid = Int32.Parse(Session["Vechid"] + "");
            string username = this.User.Identity.Name;
            var mechanicid = _unitOfWork.GetRepositoryInstance<MechanicTbl>().GetAllRecordsIQueryable().Where(a => a.UserID == username);
            int mechid = 0;
            string userid = "";
            foreach (var item in mechanicid)
            {
                mechid = item.MechanicID;
                userid = item.UserID;
            }



            ReportTbl ob = new ReportTbl();
            ob.VehicleID = vehicleid;
            ob.MechanicID = mechid;
            ob.DateOfReport = DateTime.Now;
            ob.Status = "Pending";
            db.ReportTbls.Add(ob);
            db.SaveChanges();
            var reportid = _unitOfWork.GetRepositoryInstance<ReportTbl>().GetAllRecordsIQueryable().ToList();
            int rid = 0;
            foreach (var item in reportid)
            {
                rid = item.ReportID;
            }
            using (var dbs = new ApplicationDbContext())
            {

                var cart = dbs.ReportCarts.Where(a => a.VehicleID == userid).ToList();
                ReportDetailTbl obs = new ReportDetailTbl();
                foreach (var item in cart)
                {
                    obs.ReportID = rid;
                    obs.StockID = item.StockID;
                    obs.Quantity = item.Count;
                    obs.Price = item.StockTbl.Price;
                    obs.VAT = (decimal)(0.15) * item.StockTbl.Price;
                    dbs.ReportDetailTbls.Add(obs);
                    dbs.SaveChanges();
                }
            }

            using (var b = new ApplicationDbContext())
            {
                var cart = b.ReportCarts.Where(a => a.VehicleID == userid).ToList();

                foreach (var item in cart)
                {
                    b.ReportCarts.Remove(item);
                    b.SaveChanges();
                }
            }
            using (var dbs = new ApplicationDbContext())
            {
                var temptbl = dbs.ReportQuoteTempTbls.ToList();
                var repid = _unitOfWork.GetRepositoryInstance<ReportTbl>().GetAllRecords().ToList();
                var replast = repid.Last();
                foreach (var item in temptbl)
                {
                    if (item.ReportID == 0)
                    {
                        item.ReportID = replast.ReportID;
                        dbs.SaveChanges();
                    }

                }

            }

            return RedirectToAction("ViewReports", "Mechanic");
        }


        public ActionResult ViewReports()
        {
            // int vehicleid = Int32.Parse(Session["Vechid"] + "");
            string username = this.User.Identity.Name;
            var mechanicid = _unitOfWork.GetRepositoryInstance<MechanicTbl>().GetAllRecordsIQueryable().Where(a => a.UserID == username);
            int mechid = 0;
            string userid = "";
            foreach (var item in mechanicid)
            {
                mechid = item.MechanicID;
                userid = item.UserID;
            }

            return View(_unitOfWork.GetRepositoryInstance<ReportTbl>().GetAllRecordsIQueryable().Where(a => a.MechanicID == mechid));
        }

        public ActionResult ViewReportDetails(int id)
        {
            return View(_unitOfWork.GetRepositoryInstance<ReportDetailTbl>().GetAllRecordsIQueryable().Where(a => a.ReportID == id));
        }

        public ActionResult GenerateReportFromQuote(int id)
        {
            string status = "";
            var booking = db.BookingTbls.Where(a => a.BookingID == id);

            foreach (var item in booking)
            {
                status = item.Status;
                Session["Vechid"] = item.VehicleID;
            }


            string[] qid = status.Split('#');
            int quoteid = Int32.Parse(qid[1]);
            ReportCart ob = new ReportCart();
            using (var dbs = new ApplicationDbContext())
            {
                var quotedetail = dbs.QuotationDetailTbls.Where(a => a.QuotationID == quoteid).ToList();

                foreach (var item in quotedetail)
                {
                    ob.StockID = item.StockID;
                    ob.Count = item.Quantity;
                    ob.VehicleID = this.User.Identity.Name;
                    ob.DateCreated = DateTime.Now;
                    dbs.ReportCarts.Add(ob);
                    dbs.SaveChanges();
                }


            }
            using (var ds = new ApplicationDbContext())
            {
                var bookings = ds.BookingTbls.Where(a => a.Status == status);
                foreach (var item in bookings)
                {
                    item.Status = "Assigned";

                }
                ds.SaveChanges();
            }



            return RedirectToAction("GenerateQuoteReportView", "Mechanic");
        }

        public ActionResult GenerateQuoteReportView()
        {
            return View(_unitOfWork.GetRepositoryInstance<StockTbl>().GetAllRecords());
        }

        public ActionResult ViewCompletedWork()
        {
            string username = this.User.Identity.Name;

APPDEVInc2/Controllers/ReportCartController.cs
using APPDEVInc2.Models;
using APPDEVInc2.ViewModels.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APPDEVInc2.Repository;
using APPDEVInc2.DataBaseModels;
using Microsoft.AspNet.Identity;
using System.Data;
using IronBarCode;
using System.Drawing;
using System.IO;
using APPDEVInc2.ViewModels.Mechanic;

namespace APPDEVInc2.Controllers
{
    public class ReportCartController : Controller
    {
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Cart
        public ActionResult Index()
        {
            var cart = ReportingCart.GetCart(this.HttpContext);
            var viewModel = new ReportCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);

            // var cart = _unitOfWork.GetRepositoryInstance<Cart>().GetAllRecordsIQueryable();
            // Set up our ViewModel

            // Return the view
            //var viewModel = cart;

        }
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProduct = db.StockTbls
                .Single(product => product.StockID == id);

            // Add it to the shopping cart
            var cart = ReportingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main Quotation Items to add
            return RedirectToAction("GenerateReport", "Mechanic" , new { id = Int32.Parse(Session["Vechid"]+"")});
        }

        // Increase QTY Checkout
        public ActionResult IncreaseQTY(int id)
        {
            HttpContext context = System.Web.HttpContext.Current;
            // var prods = db.TyresTbls.Single(a => a.TyreID == id);
            var x = db.StockTbls.Single(a => a.StockID == id);
            string cid = "";

            int stockid = x.StockID;

            var cart1 = _unitOfWork.GetRepositoryInstance<ReportCart>().GetAllRecords();
            var last = cart1.Last();
            cid = context.User.Identity.Name;

            string cartid = context.Session["ReportCartId"].ToString();
            if (cid != null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.ReportCarts.Where(a => a.VehicleID == cartid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID ==cartid && item.StockID == id)
                        {
                            item.Count += 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.ReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };
            }
            if (cid == null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.ReportCarts.Where(a => a.VehicleID == cartid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cid && item.StockID == id)
                        {
                            item.Count += 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.ReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };

            }


            return RedirectToAction("Index");
        }

        // Decrease QTY Checkout
        public ActionResult DecreaseQTY(int id)
        {
            HttpContext context = System.Web.HttpContext.Current;
            var car = new ReportCart();
            string cid = "";
            var x = db.StockTbls.Single(a => a.StockID == id);
            int stockid = x.StockID;

            var cart1 = _unitOfWork.GetRepositoryInstance<ReportCart>().GetAllRecords();
            var last = cart1.Last();
            cid = context.User.Identity.Name;
            string cartid = context.Session["ReportCartId"].ToString();

            if (cid != null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.ReportCarts.Where(a => a.VehicleID == cartid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cartid && item.StockID == id)
                        {
                            item.Count -= 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.ReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };
            }
            if (cid == null)
            {
                using (var dbs = new ApplicationDbContext())
                {
                    var cart = dbs.ReportCarts.Where(a => a.VehicleID == cid).ToList();
                    foreach (var item in cart)
                    {
                        if (item.VehicleID == cid && item.StockID == id)
                        {
                            item.Count -= 1;
                            dbs.SaveChanges();
                            if (item.Count == 0)
                            {
                                dbs.ReportCarts.Remove(item);
                                dbs.SaveChanges();
                            }
                        }
                    }
                };

            }

            return RedirectToAction("Index");
        }

        public ActionResult CheckoutDetail()
        {

            string name = this.HttpContext.User.ToString();


            var cart = ReportingCart.GetCart(this.HttpContext);

            var viewModel = new ReportCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()

            };

            return View(viewModel);
        }

        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult ReportCartSummary()
        {
            var cart = ReportingCart.GetCart(this.HttpContext);

            ViewData["ReportCartCount"] = cart.GetCount();
            return PartialView("ReportCartSummary");
        }

    }
}

APPDEVInc2/Views/Mechanic/CapturePaymentForCalloutInvoice.cshtml
@model IEnumerable<APPDEVInc2.DataBaseModels.CalloutReportDetailTbl>


@{
    ViewData["Title"] = "Payment Method";
    Layout = "~/Views/Shared/_LayoutMechanic.cshtml";
}

<br />
<br />
<br />
<br />
<br />

<form method="post">

    <br />
    @{
        decimal total = 0;
        int reportid = 0;
    }

    <div class="align-content-center">
        <div class="container">
            <div class="card-header bg-dark text-light ml-0 row container">
                <div class="col-6">
                    <i class="fa fa-shopping-cart"></i> &nbsp;
                    Payment Selection:
                </div>

            </div>
            <div class="card-body">
                @foreach (var item in Model)
                {




                    reportid = item.CalloutReportID;

                    total += (decimal)(item.Price * item.Quantity);
                }
                <h4><strong>Payment Total: R @total</strong></h4>

            </div>

        </div>


    </div>



    <a class="btn btn-danger" href=@Url.Action("PayNow", "PayFastMechanic", new { id = reportid}) style="background-color: #0bfc03;
        color: black;
        font-size: 18px;
        font-family: 'Lato', sans-serif;
        font-weight: bold;
        border-color: #9be50f;
        text-align: center;
        justify-content: center;
        width: 240px;">CARD/VISA</a>
    <a class="btn btn-danger" href=@Url.Action("CashPayment", "Mechanic",new { id = reportid}) style="background-color: #0bfc03;
        color: black;
        font-size: 18px;
        font-family: 'Lato', sans-serif;
        font-weight: bold;
        border-color: #9be50f;
        text-align: center;
        justify-content: center;
        width: 240px;">CASH</a>

</form>

APPDEVInc2/Views/Mechanic/GenerateQuoteReportView.cshtml
@model IEnumerable<APPDEVInc2.DataBaseModels.StockTbl>

@{ ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>

<style>
    tbody {
        font-family: 'Lato', sans-serif;
        font-size: 18px;
        color: black;
        padding-top: 5px;
    }

    body {
        background-color: #cccaca;
    }

    .fas fa-list-alt {
        color: black;
        text-align: left;
        justify-content: left;
    }

    .CategroyPageHeading {
        color: #1c8219;
        text-align: center;
        justify-content: center;
        font-family: Arial;
        font-size: 21px;
        font-weight: bold;
    }

    th {
        background-color: white;
        font-size: 16px;
        font-family: 'Lato', sans-serif;
        color: #0771ab;
        text-transform: uppercase;
        letter-spacing: 0.03em;
        font-weight: bold;
    }

    .breadcrumb {
        border-radius: 10px;
        background-color: white;
        box-shadow: 0px 0 6px 0 #545454;
        font-size: 18px;
    }

    .card {
        border: 2px;
        border-color: white;
        box-shadow: 0px 0 6px 0 #000000;
    }

    .card-header {
        background-color: white;
        border-radius: 20px;
    }

    ol li a {
        color: #ff007d;
    }

    .editlabel a {
        font-size: 18px;
        font-family: 'Lato', sans-serif;
        color: black;
    }

    .table-responsive {
        border-radius: 5px 5px 5px 5px;
    }

    .pagination {
        background-color: white;
        color: black;
        font-size: 18px;
        border-color: white;
    }

    .fa .fa-plus {
        color: #ffd800;
    }

    .pageheader {
        font-family: 'Abril Fatface', cursive;
        font-size: 27px;
        color: black;
        text-align: center;
        justify-content: center;
    }

    .AdminCategories {
        width: 25%;
        height: 21%;
    }

    tr:nth-child(odd) {
        background-color: #d1eaea;
    }
</style>

<h2 class="pageheader">Vees Tyre and Alignment</h2>
<br />
<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a style="font-weight:bold;" href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Generate Report For Vehicle</li>

    </ol>

    <div class="card mb-3">
        <div class="card-header">
            <br />
            <h2 class="CategroyPageHeading">CONTINUE REPORT FROM QUOTE</h2>

        </div>
        <h3>Your Current Report : @{Html.RenderAction("ReportCartSummary", "ReportCart"); }</h3>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Item/Service ID</th>
                            <th>Name</th>
                            <th>Item/Service Name</th>
                            <th>Description</th>
                            <th>Price</th>

                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            int count = 1;


                            <tr>
                                @if (item.ServiceID == 1)
                                {
                                    <td>@item.StockID</td>
                                    <td>@item.ServiceTbl.Name</td>
                                    <td>@item.TyresTbl.TyreName</td>
                                    <td>@item.TyresTbl.TyreBrand</td>

                                    <td>R @item.Price</td>
                                }
                                @if (item.ServiceID != 1)
                                {
                                    <td>@item.StockID</td>
                                    <td>@item.ServiceTbl.Name</td>
                                    <td>@item.ServiceTbl.Name</td>
                                    <td>@item.ServiceTbl.Description</td>
                                    <td>R @item.Price</td>

                                }



                                <td>

                                    <button onclick="cartMessage()"><a>@Html.ActionLink("Add to Report ", "AddToCart", "ReportCart", new { id = item.StockID }, "")</a><i class="fa fa-shopping-cart"></i></button>
                                </td>

                            </tr>
                            count++;
                        }

                    </tbody>
                </table>
            </div>





        </div>
    </div>
</div>


<script>
function cartMessage() {
        alert("Item added to Report")
    }</script>

APPDEVInc2/Views/Mechanic/GenerateReport.cshtml
@model IEnumerable<APPDEVInc2.DataBaseModels.StockTbl>

@{ ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_LayoutMechanic.cshtml"; }

<link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>

<style>
    tbody {
        font-family: 'Lato', sans-serif;
        font-size: 18px;
        color: black;
        padding-top: 5px;
    }

    body {
        background-color: #cccaca;
    }

    .fas fa-list-alt {
        color: black;
        text-align: left;
        justify-content: left;
    }

    .CategroyPageHeading {
        color: #1c8219;
        text-align: center;
        justify-content: center;
        font-family: Arial;
        font-size: 21px;
        font-weight: bold;
    }

    th {
        background-color: white;
        font-size: 16px;
        font-family: 'Lato', sans-serif;
        color: #0771ab;
        text-transform: uppercase;
        letter-spacing: 0.03em;
        font-weight: bold;
    }

    .breadcrumb {
        border-radius: 10px;
        background-color: white;
        box-shadow: 0px 0 6px 0 #545454;
        font-size: 18px;
    }

    .card {
        border: 2px;
        border-color: white;
        box-shadow: 0px 0 6px 0 #000000;
    }

    .card-header {
        background-color: white;
        border-radius: 20px;
    }

    ol li a {
        color: #ff007d;
    }

    .editlabel a {
        font-size: 18px;
        font-family: 'Lato', sans-serif;
        color: black;
    }

    .table-responsive {
        border-radius: 5px 5px 5px 5px;
    }

    .pagination {
        background-color: white;
        color: black;
        font-size: 18px;
        border-color: white;
    }

    .fa .fa-plus {
        color: #ffd800;
    }

    .pageheader {
        font-family: 'Abril Fatface', cursive;
        font-size: 27px;
        color: black;
        text-align: center;
        justify-content: center;
    }

    .AdminCategories {
        width: 25%;
        height: 21%;
    }

    tr:nth-child(odd) {
        background-color: #d1eaea;
    }
</style>

<h2 class="pageheader">Vees Tyre and Alignment</h2>
<br />
<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a style="font-weight:bold;" href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Generate Report For Vehicle</li>

    </ol>

    <div class="card mb-3">
        <div class="card-header">
            <br />
            <h2 class="CategroyPageHeading">GENERATE REPORT</h2>

        </div>
        <h3>Your Current Report : @{Html.RenderAction("ReportCartSummary", "ReportCart"); }</h3>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Item/Service ID</th>
                            <th>Name</th>
                            <th>Item/Service Name</th>
                            <th>Description</th>
                            <th>Price</th>

                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            int count = 1;


                            <tr>
                                @if (item.ServiceID == 1)
                                {
                                    <td>@item.StockID</td>
                                    <td>@item.ServiceTbl.Name</td>
                                    <td>@item.TyresTbl.TyreName</td>
                                    <td>@item.TyresTbl.TyreBrand</td>

                                    <td>R @item.Price</td>
                                }
                                @if (item.ServiceID != 1)
                                {
                                    <td>@item.StockID</td>
                                    <td>@item.ServiceTbl.Name</td>
                                    <td>@item.ServiceTbl.Name</td>
                                    <td>@item.ServiceTbl.Description</td>
                                    <td>R @item.Price</td>

                                }



                                <td>

                                    <button onclick="cartMessage()"><a>@Html.ActionLink("Add to Report ", "AddToCart", "ReportCart", new { id = item.StockID }, "")</a><i class="fa fa-shopping-cart"></i></button>
                                </td>

                            </tr>
                            count++;
                        }

                    </tbody>
                </table>
            </div>





        </div>
    </div>
</div>


<script>
function cartMessage() {
        alert("Item added to Report")
    }</script>